name: Project Automation

on:
  issues:
    types: [opened, edited, labeled, unlabeled, closed, reopened]
  pull_request:
    types: [opened, edited, labeled, unlabeled, closed, reopened, synchronize]
  project_card:
    types: [created, edited, moved, converted, deleted]
  schedule:
    - cron: '0 9 * * 1-5' # Weekdays at 9 AM

jobs:
  automate-project:
    name: Update Project Board
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run project automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/project-automation.js

  weekly-report:
    name: Generate Weekly Report
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate project report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          node .github/scripts/generate-weekly-report.js

  stale-issues:
    name: Mark Stale Issues
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Mark stale issues
        uses: actions/stale@v8
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: 'This issue has been marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs.'
          close-issue-message: 'This issue was closed because it had been inactive for 30 days.'
          stale-issue-label: 'stale'
